name: BR CI
on:
  push:
    branches: main
    paths: br/**
  pull_request:
    branches: main
    paths: br/**

permissions:
  contents: read

jobs:
  golangci-lint:
    name: Run golangci lint for TiKV BR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
          working-directory: br
          args: -v $(go list ./...| grep "github.com\/tikv\/migration\/br" | sed 's|github.com/tikv/migration/br/||') --config ../.golangci.yml --allow-parallel-runners --timeout=3m
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: gosec
        uses: securego/gosec@master
        with:
          version: v2.9.1
          working-directory: br
          args: -fmt=junit-xml -out=results.xml -stdout -verbose=text -exclude=G103,G104,G204,G304,G307,G401,G404,G501,G505,G601 ./...
