name: BR Golangci Lint
on:
  push:
    branches: main
    paths: br/**
  pull_request:
    branches: main
    paths: br/**

permissions:
  contents: read

jobs:
  golangci-br:
    name: Run golangci lint for TiKV BR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
          working-directory: br
          args: -v $(go list ./...| grep "github.com\/tikv\/migration\/br" | sed 's|github.com/tikv/migration/br/||') --config ../.golangci.yml --allow-parallel-runners --timeout=3m
